### ISSUE TITLE
ID length does not have to be 5 

### ISSUE THREAD

**Issue by benjsnellings** [bobbyblues/pyslidebar#1]
My slidebar ID is 6 characters to it starts throwing errors.

('Error when converting value:', u'l1n105')
l1n105
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/ben/workspace/pyslidebar/slidebar.py", line 42, in reader
    pos_float = float(value) / 1023.0
ValueError: could not convert string to float: l1n105

**Comment by bobbyblues** [comment]
I changed the rule, and am now checking if the letter 'l' is present in what I am reading.
It is probably not ideal as future slidebar model id's may not start with 'l', but it should be good enough to get it to work for now.

Thanks for the feedback!

**Comment by benjsnellings** [comment]
I am working on some code to do a PR. it looks like all the values sent in are 4 or less, so i can use that as a baseline to find the ID

**Comment by bobbyblues** [comment]
Yes, but I'm thinking the first 10 slidebars created will have for ids l1n1, l1n2 etc. which are four characters as well, hence me looking for an 'l'.

I'm still sure there is a better solution though.
